//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diamonds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diamonds()
        {
            this.diamondStatus = new HashSet<diamondStatus>();
            this.traderDiamonds = new HashSet<traderDiamonds>();
        }
    
        public int diamondId { get; set; }
        public string diamondName { get; set; }
        public Nullable<int> cleanLevelId { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> shapeId { get; set; }
        public Nullable<double> CT { get; set; }
    
        public virtual cleanLevels cleanLevels { get; set; }
        public virtual colors colors { get; set; }
        public virtual shapes shapes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diamondStatus> diamondStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traderDiamonds> traderDiamonds { get; set; }
    }
}
