//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class diamondStatus
    {
        public int diamondStatusId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> diamondId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> professionalId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> CT { get; set; }
    
        public virtual Diamonds Diamonds { get; set; }
        public virtual professionales professionales { get; set; }
        public virtual status status { get; set; }
    }
}
