//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiampndsDBEntities : DbContext
    {
        public DiampndsDBEntities()
            : base("name=DiampndsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cleanLevels> cleanLevels { get; set; }
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<Diamonds> Diamonds { get; set; }
        public virtual DbSet<diamondStatus> diamondStatus { get; set; }
        public virtual DbSet<priceList> priceList { get; set; }
        public virtual DbSet<professionales> professionales { get; set; }
        public virtual DbSet<shapes> shapes { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<traderDiamonds> traderDiamonds { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
